### ISSUE TITLE
Rails boot fails due to JOR incompatibility with mysql2 gem v0.3[.21]                                                                                                   ruby-2.5.5@global

### ISSUE THREAD

**Issue by saveriomiroddi** [saveriomiroddi/json_on_rails#16]
Although Rails 5.1 is not a supported by the Rails team, it requires a mysql2 gem version, ~> 0.3, which is formally supported by JOR. Either fix it, or remove the support.

May be related to #15.

Error and relevant stacktrace:

```
<gems_root>/activesupport-4.1.0/lib/active_support/values/time_zone.rb:285: warning: circular argument reference - now
<gems_root>/json_on_rails-0.2.0/lib/active_record/type/json.rb:11:in `<module:Type>': uninitialized constant ActiveRecord::Type::Value (NameError)
  from <gems_root>/json_on_rails-0.2.0/lib/active_record/type/json.rb:10:in `<module:ActiveRecord>'
  from <gems_root>/json_on_rails-0.2.0/lib/active_record/type/json.rb:9:in `<top (required)>'
  from <gems_root>/json_on_rails-0.2.0/lib/active_record/connection_adapters/mysql2_json_adapter.rb:4:in `require'
  from <gems_root>/json_on_rails-0.2.0/lib/active_record/connection_adapters/mysql2_json_adapter.rb:4:in `<top (required)>'
  from <gems_root>/json_on_rails-0.2.0/lib/json_on_rails.rb:4:in `require_relative'
  from <gems_root>/json_on_rails-0.2.0/lib/json_on_rails.rb:4:in `<top (required)>'
  [...]
```

**Comment by saveriomiroddi** [comment]
Duplicate of #15.
